### ISSUE TITLE
SpotifyHandler will not correctly return a user client if requested

### ISSUE THREAD

**Issue by iHeroGH** [AlecUrbany/CS4800-SentiSounds#5]
If a SpotifyHandler is initialized with _initialize_base_client, _client_instance will be populated and therefore will be returned when get_user_client is called (even though a user client was requested)

I am still unsure how the SpotifyHandler will be communicated to once we begin implementing the rest of the application, but this feels like something that will come up later

**Comment by wesleyd02** [comment]
What if you introduce an additional attribute _is_user_client to track whether the client instance is a user client or not. Then check both the existence of the client instance and the value of is_user_client to determine which client to return.

**Comment by iHeroGH** [comment]
Either that or the base client instance is static throughout all SpotifyHandler objects, and the user client is instantiated by the programmer during execution (and retrieved if it's available). We'll still need to research how to more comfortably allow a user to sign-in and authenticate first before we make changes to the code, I believe, but it's important to note that this'll need an update _at some point eventually_

**Comment by meap02** [comment]
I was assuming that each instance of the class would be created each web session. I could include a method to "switch_to_user_client" if they decide to connect their Spotify account, would that fix our issue?

**Comment by iHeroGH** [comment]
*I* was assuming;

Website turns on > SpotifyHandler has a base client initialized for all non-Spotify authenticated users

User logs in via Spotify > a SpotifyHandler *instance* is made with the authenticated user stuff

What do you think?

(I *believe* either way works...)

**Comment by meap02** [comment]
That could work, only thing I'd be worried about is the timeout on the Spotify API token, even for no user, the token will need to be re-authenticated after a certain amount of time

**Comment by iHeroGH** [comment]
Gotcha, that's enough reason to have it be non-static for both then. switch_... LGTM then
