### ISSUE TITLE
Discord hosted images

### ISSUE THREAD

**Issue by meap02** [AlecUrbany/CS4800-SentiSounds#9]
In commits e06c429, c65752e, d257b3a, and 2ea3451, I found some links to an image hosted by discord within the HTML such as:

```
<div class="mb-10 text-center">
            <img src="https://cdn.discordapp.com/attachments/1201987045799493673/1210420109072408626/KzFf0DN9bzAAAAAElFTkSuQmCC.png?ex=6621dd92&is=660f6892&hm=777b85b4e62159087f78ed6dd60c6bb94d1c125865f354daccb0e303b808f857&"
                alt="SentiSounds logo" class="mb-3 mx-auto" style="width: 100px; height: 100px;">
            <h1 class="text-3xl text-white font-bold">SentiSounds</h1>
            <p class="text-[#D19900]">code is awesome - jack | code is cool - SAM</p>
        </div>
```

Please have all of the assets needed for the webpage located in a local directory. I don't want the website to break if discord cannot be reached or if the images are deleted from discord's servers.

**Comment by iHeroGH** [comment]
Further, Discord CDN links have recently been updated to include an expiry time. The links will, at some point, be unusable.

**Comment by chungsamuel** [comment]
added asset folder with image
